JAlarconPruebaTecnica2/Controllers/DiscoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAlarconPruebaTecnica2.Controllers
{
    public class DiscoController : Controller
    {
        // GET: Disco
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Disco disco = new ML.Disco();

            var result = BL.Disco.GetAll();

            if (result.Correct)
            {
                disco.Discos = result.Objects.ToList();
            }
            return View(disco);
        }

        [HttpPost]
        public ActionResult GetAll(ML.Disco disco) {
           
            disco = new ML.Disco();
            ML.Result result = BL.Disco.GetAll();
            disco.Discos = result.Objects;

            return View(disco);

        }




        [HttpGet]
        public ActionResult Form(int? IdDisco)
        {
            ML.Disco disco = new ML.Disco();

            if (IdDisco != null)
            {
                ML.Result result = BL.Disco.GetByI(IdDisco.Value);

                if (result.Correct)
                {

                    disco = (ML.Disco)result.Object;

                }

            }
         


            return View(disco);
        }

        [HttpPost]
        public ActionResult Form(ML.Disco disco)
        {
            if(ModelState.IsValid) { 

            if (disco.IdDisco == 0)
            {
                ML.Result result = BL.Disco.Add(disco);

                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se ha completado el registro";
                }
                else
                {
                    ViewBag.Mensaje = "Error" + result.ErrorMessage;
                }

            }

            }
            else
            {
                ML.Result result = BL.Disco.Update(disco);
                if (result.Correct)
                {

                    ViewBag.Mensaje = "Se ha completado la actualizacion";
                }
                else
                {
                    ViewBag.Mensaje = "Error" + result.ErrorMessage;
                }
            }


            return PartialView("Modal");
        }


        [HttpGet]
        public ActionResult Delete(int IdDisco)
        {

            ML.Result result = BL.Disco.Delete(IdDisco);
            if (result.Correct)
            {
                ViewBag.Mensaje = "Se ha eleiminado correctamente el departamento";

            }
            else
            {
                ViewBag.Mensaje = "No se ha podido eliminar el departamento" + result.ErrorMessage;
            }
            return PartialView("Modal");
        }

    }
}

JAlarconPruebaTecnica2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAlarconPruebaTecnica2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JAlarconPruebaTecnica2/Views/Disco/Form.cshtml
@model ML.Disco
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

}
<br>
<div class="text-center">
    <h2 class="display-6">Formulario</h2>
</div>
<br>
@using (Html.BeginForm("Form", "Disco", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-3">
            @Html.HiddenFor(model => model.IdDisco)


            @Html.LabelFor(model => model.Titulo)

            @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control bloquear" })
            <br>

        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.Artista)
            @Html.TextBoxFor(model => model.Artista, new { @class = "form-control bloquear" })
            <br>

        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.GeneroMusical)
            @Html.TextBoxFor(model => model.GeneroMusical, new { @class = "form-control bloquear" })
            <br>
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.Duracion)
            @Html.TextBoxFor(model => model.Duracion, new { @class = "form-control bloquear" })
            <br>
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.Año)
            @Html.TextBoxFor(model => model.Año, new { @class = "form-control bloquear" })
            <br>
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.Distribuidora)
            @Html.TextBoxFor(model => model.Distribuidora, new { @class = "form-control bloquear" })
            <br>
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.Ventas)
            @Html.TextBoxFor(model => model.Ventas, new { @class = "form-control bloquear" })
            <br>
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.Distribuidora)
            @Html.TextBoxFor(model => model.Disponibilidad, new { @class = "form-control bloquear" })
            <br>
        </div>










        <!-- Final de los campos -->
    </div>
    <br>
    <div class="text-center">
        <button id="btnGuardar" class="btn btn-success" type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
        <a id="btnCancelar" class="btn btn-danger" href="@Url.Action("GetAll", "Disco")"><i class="fa-solid fa-right-from-bracket"></i> Volver</a>
    </div>
    <br>


    @Scripts.Render("~/bundles/jquery")



    <script>


        $("#btnGuardar").mouseenter(function () {
            $("#btnGuardar").addClass("fa-bounce").removeClass("btn-success").mouseout(function () {
                $("#btnGuardar").addClass("btn-success").removeClass("fa-bounce")



            })

        });


        $("#btnCancelar").mouseenter(function () {
            $("#btnCancelar").addClass("fa-bounce").removeClass("btn-danger").mouseout(function () {
                $("#btnCancelar").removeClass("fa-bounce").addClass("btn-danger")



            })

        });

    </script>





}

JAlarconPruebaTecnica2/Views/Disco/GetAll.cshtml
@model ML.Disco
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

}

<h2 class="h4">Discos.</h2>

@using (Html.BeginForm("GetAll", "Disco", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <td><a class="btn btn-outline-dark" href="@Url.Action("Form", "Disco")"><i> Agregar disco</i></a></td>
    <br>
    <div class="table-responsive">
        <div class="container">
            <table class="table table-striped table-bordered" id="myTable">
                <thead>
                    <tr>
                        <th>Actualizar</th>
                        <th>IdDisco</th>
                        <th>Titulo</th>
                        <th>Artista</th>
                        <th>GeneroMusical</th>
                        <th>Duracion</th>
                        <th>Año</th>
                        <th>Distribuidora</th>
                        <th>Ventas</th>
                        <th>Disponibilidad</th>
                        <th>Borrar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Disco disco in Model.Discos)
                    {
                        <tr>
                            <td><a class="btn btn-warning" href="@Url.Action("Form", "Disco", new {IdDisco = disco.IdDisco})"></a><i class="bi bi-vector-pen">Actualizar disco.</i></td>
                            <td>@disco.IdDisco</td>
                            <td>@disco.Titulo</td>
                            <td>@disco.Artista</td>
                            <td>@disco.GeneroMusical</td>
                            <td>@disco.Duracion</td>
                            <td>@disco.Año</td>
                            <td>@disco.Distribuidora</td>
                            <td>@disco.Ventas</td>
                            <td>@disco.Disponibilidad</td>
                            <td><a class="btn btn-danger" href="@Url.Action("Delete", "Disco", new { IdDisco = disco.IdDisco })" onclick="return confirm('Seguro que quieres borrar el disco?')"><i class="fa-solid fa-trash-can"></i></a></td>
                        </tr>

                    }

                </tbody>
            </table>

        </div>
    </div>

}

<script type="text/javascript">
    let table = new DataTable('#myTable', {
        responsive: true,
        "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "Todos"]],
        searching: false,
        language: {
            url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
        },
    });
</script>

JAlarconPruebaTecnica2/Views/Disco/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@

                    @Html.ActionLink("Vale", "GetAll", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })


            </div>

        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

JAlarconPruebaTecnica2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

JAlarconPruebaTecnica2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

JAlarconPruebaTecnica2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

JAlarconPruebaTecnica2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <li><img src="https://th.bing.com/th/id/OIP.R8hsfjQbFrgZpiIQmDdCOwHaFj?pid=ImgDet&rs=1" class="img-thumbnail" height="30px" width="30px"></li>
            @Html.ActionLink("Disquera", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Disco", "GetAll", "Disco", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>